[package]
name = "wgpu-template"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.21.0", features = ["derive"] }
cgmath = "0.18.0"
pollster = "0.4.0"
wgpu = "24.0.0"
winit = { version = "0.29", features = ["rwh_05"] }
